---
projects:
  - name: affiliate
    path: /extrovert/current
  - name: express
    path: /express/current
  - name: deals_mgmt
    path: /data/deals-mgmt/current
  - name: deals
    path: /data/gems/deals
  - name: urn_identifiable
    path: /data/gems/urn_identifiable

hosts:
  - hostname: mxxqa01.mmx.local
    username: express
    password: XpR3$$
  - hostname: mxxqa02.mmx.local
    username: express
    password: XpR3$$
  - hostname: mxxqa03.mmx.local
    username: express
    password: XpR3$$
  - hostname: mxxqa04.mmx.local
    username: express
    password: XpR3$$
